version: 2.1
executors:
  app-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
aliases:
  - &show-current-branch-name
    run:
      name: Show current branch name
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
        - app-
  - &save-cache
    save_cache:
      key: app-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
      paths:
        - ./node_modules
        - ./.next/cache
  - &install-dependencies
    run:
      name: Install dependencies
      command: |
        mkdir -p artifacts
        npm install
  - &build-project
    run:
      name: Build project
      command: |
        npm install
        npm run build 
        echo "Build completed"
  - &setup-git-user
    run:
      name: Setup git user
      command: |
        git.config.global.username ${GIT_USERNAME}
        git.config.global.email ${GIT_EMAIL}      
  - &merge-to-dev
    run:
      name: Merge feature to dev
      command: |
        git checkout develop
        git merge ${CIRCLE_BRANCH}
        git push origin develop
  - &merge-dev-to-main
    run:
      name: Merge develop to main branch
      command: |
        git checkout main
        git merge develop
        git push origin main
jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache
      - *build-project
  git:
     executor: app-executor
     steps:
       - checkout
       - *setup-git-user
       - *merge-to-dev
       - *merge-dev-to-main
  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: run linting
          command: npm run lint

  prettier:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: run prettier check
          command: npm run prettier

workflows:
  build_and_deploy:
    jobs:
      - build
      - linting:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - develop 
      - prettier:
          requires:
            - linting
          filters:
             branches:
               only:
                 - main
                 - develop
      - git:
         requires:
           - prettier
          
