export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_16_DAY_FORECAST = 'GET_16DAY_FORECAST';
export const GET_DAY_DETAILS = 'GET_DAY_DETAILS';
export const SET_ACTIVE_CARD_INDEX = 'SET_ACTIVE_CARD_INDEX';
